### ISSUE TITLE
Not suggesting path when creating second path on the same line

### ISSUE THREAD

**Issue by JosefLitos** [hrsh7th/cmp-path#28] opened 2021-12-24 08:34 UTC
Lets say I have a line:
```sh
/usr/bin/java -jar /usr/local/bin/file.jar
```
The first path will be completed, but the path to the second file I have to know, since it won't give me any suggestion on the same line.
Is there anything that could be done about this?

**Comment by Ultra-Code** [comment] 2022-03-15 20:38
I have been having this very same issue for a very long time now. I would love to see this been fixed

**Comment by Galicarnax** [comment] 2022-07-23 12:07
Just wanted to open the issue for that, and noticed it already exists.

Probably, the issue is that the completion engine doesn't know that you are dealing with another path, and thinks it's a continuation of the first one, only with weird directory names (like `java -jar /`).

**Comment by JosefLitos** [comment] 2022-07-24 07:21
this could be fixed by regarding ' /' as a beginning of a new path since noone would name a directory with a trailing space

**Comment by hrsh7th** [comment] 2022-07-26 07:43
Fixed by https://github.com/hrsh7th/cmp-path/commit/bee12940fd4b3ec6238f43ba2c5515fa3e018e96

**Closed by hrsh7th** 2022-07-26 07:43 UTC

**Comment by JosefLitos** [comment] 2022-07-26 08:55
But this fix disables the spaces altogether. We only need to test for a trailing space.

**Comment by Ultra-Code** [comment] 2022-07-27 12:26
Works for my use case. Thank you for taking time to get this fixed.
